# Generated by Django 2.1.2 on 2018-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=99),
        ),
    ]
