# Generated by Django 2.1.2 on 2018-11-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20181124_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='name',
            new_name='user',
        ),
    ]
