# Generated by Django 2.1.2 on 2018-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
