# Generated by Django 2.1.2 on 2018-10-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0002_auto_20181019_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='new_shop.Category'),
            preserve_default=False,
        ),
    ]
