# Generated by Django 2.1.2 on 2018-10-23 07:30

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0005_auto_20181023_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_shop.Category'),
        ),
    ]
