# Generated by Django 2.1.2 on 2018-10-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0006_auto_20181023_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='rodcat',
            new_name='parent',
        ),
    ]
