# Generated by Django 2.1.2 on 2018-10-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0008_auto_20181031_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zacaz',
            name='items',
        ),
        migrations.AddField(
            model_name='zacaz',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new_shop.Card'),
        ),
    ]
