# Generated by Django 2.1.2 on 2018-11-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0009_auto_20181031_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='zacaz',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
