# Generated by Django 2.1.2 on 2018-11-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0010_auto_20181105_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zacaz',
            name='status',
            field=models.CharField(choices=[('1', 'В обработке'), ('2', 'Доставка'), ('3', 'Готово')], default='1', max_length=10, verbose_name='статус заказа'),
        ),
    ]
