# Generated by Django 2.1.2 on 2018-12-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_shop', '0016_auto_20181213_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
